services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: mashi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mashistore_dev
    ports:
      - "5433:5432"   # host:container -> changed host port to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
